### ISSUE TITLE
Unable to start the client.

### ISSUE THREAD

**Issue by EliMCGamerGuy** [madprogrammer/singingmonsters-bot#13]
I went through and added all the dependencies and tried to start the client, but it just crashes.
hope this gets figured out, or maybe i'm just a dummy who did it wrong. either way, i hope it's salvageable.

here's what the crash spits out:
```PS E:\Programs\SingingMonsters-Bot> bundle exec ruby main.rb
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mustermann-1.0.1/lib/mustermann/regular.rb:22:in `initialize': wrong number of arguments (given 2,
expected 1) (ArgumentError)
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mustermann-1.0.1/lib/mustermann/pattern.rb:59:in `new'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mustermann-1.0.1/lib/mustermann/pattern.rb:59:in `block in new'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mustermann-1.0.1/lib/mustermann/equality_map.rb:39:in `fetch'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mustermann-1.0.1/lib/mustermann/pattern.rb:59:in `new'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mustermann-1.0.1/lib/mustermann.rb:67:in `new'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mustermann-1.0.1/lib/mustermann.rb:70:in `block in new'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mustermann-1.0.1/lib/mustermann.rb:70:in `map'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/mustermann-1.0.1/lib/mustermann.rb:70:in `new'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1638:in `compile'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1626:in `compile!'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1268:in `error'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1836:in `<class:Base>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:894:in `<module:Sinatra>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:22:in `<top (required)>'
        from main.rb:2:in `require'
        from main.rb:2:in `<main>'
PS E:\Programs\SingingMonsters-Bot>

**Comment by madprogrammer** [comment]
Running under Windows is not supported, please see updated installation instructions and use Ubuntu 20.04 LTS running in WSL/WSL2 or install a virtual machine using VirtualBox.
