### ISSUE TITLE
I have no idea what im doing

### ISSUE THREAD

**Issue by Niceghost21** [madprogrammer/singingmonsters-bot#14]
Hello!  I tried using this, but i don't quite understand how to use ruby or any of this.  Once I entered bundle exec ruby main.rb, I get this log.

bundle exec ruby main.rb
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Traceback (most recent call last):
        5: from main.rb:3:in `<main>'
        4: from main.rb:3:in `require'
        3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.5-x64-mingw32/lib/eventmachine.rb:8:in `<top (required)>'
        2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.5-x64-mingw32/lib/eventmachine.rb:8:in `require'
        1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.5-x64-mingw32/lib/rubyeventmachine.rb:2:in `<top (required)>'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.5-x64-mingw32/lib/rubyeventmachine.rb:2:in `require': cannot load such file -- 2.7/rubyeventmachine (LoadError)

**Comment by Niceghost21** [comment]
I did this; go to this folder C:\Ruby24-x64\lib\ruby\gems\2.4.0\gems\eventmachine-1.2.5-x64-mingw32\lib
open this file eventmachine.rb
write this
require 'em/pure_ruby'
in the first line of code in the file

This fixed that problem but now I get this error 
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thin-1.7.2/lib/thin/backends/tcp_server.rb:18:in `unpack_sockaddr_in': no implicit conversion of nil into String (TypeError)
