### ISSUE TITLE
Pregame setup filed in 'login'

### ISSUE THREAD

**Issue by JosephOBr** [madprogrammer/singingmonsters-bot#22]
When I try to run bundle exec ruby main.rb, I get the following output:
== Sinatra (v2.1.0) has taken the stage on 4567 for development with backup from Thin
2022-12-21 12:22:08 +1100 Thin web server (v1.8.0 codename Possessed Pickle)
2022-12-21 12:22:08 +1100 Maximum connections set to 1024
2022-12-21 12:22:08 +1100 Listening on 0.0.0.0:4567, CTRL+C to stop
{"ok":true,"user_game_id":["49ckbbybtv"],"login_types":"[email]","access_token":"3WuIxHCZcQOkkX2lk559xwSe4DeXbc8viEUKspWClq4CBDFdfn6tSzhCluoxBhj\/rXb0Tcc9JRr\/ni\/3UjRLpjL5S\/YzEmcXSrZO+\/fQFiVNh69Jdlq5N1kFuAiCJdmBMFFIlshwjkbYH13G1SHxGRaeHiqwwWAzfsfu287fOIWD7V+AgGy0O2gJhLNofTlEMJrGGAlGkIqpLTgEqQx9zhfEOnzUP6bunDIzElGmLkPtentHmAGeeXDs3kY89fR1dcghxwJP1aW2lQ==","token_type":"bearer","expires_at":1671586401}
{"ok":false,"error":21,"message":"https://play.google.com/store/apps/details?id=com.bigbluebubble.singingmonsters.full"}
2022-12-21 12:22:11 +1100 Stopping ...
== Sinatra has ended his set (crowd applauds)
Traceback (most recent call last):
	12: from main.rb:122:in `<main>'
	11: from /home/joseppi/Downloads/singingmonsters-bot/vendor/bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1499:in `run!'
	10: from /home/joseppi/Downloads/singingmonsters-bot/vendor/bundle/ruby/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1565:in `start_server'
	 9: from /home/joseppi/Downloads/singingmonsters-bot/vendor/bundle/ruby/2.7.0/gems/thin-1.8.0/lib/rack/handler/thin.rb:22:in `run'
	 8: from /home/joseppi/Downloads/singingmonsters-bot/vendor/bundle/ruby/2.7.0/gems/thin-1.8.0/lib/thin/server.rb:162:in `start'
	 7: from /home/joseppi/Downloads/singingmonsters-bot/vendor/bundle/ruby/2.7.0/gems/thin-1.8.0/lib/thin/backends/base.rb:75:in `start'
	 6: from /home/joseppi/Downloads/singingmonsters-bot/vendor/bundle/ruby/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	 5: from /home/joseppi/Downloads/singingmonsters-bot/vendor/bundle/ruby/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	 4: from /home/joseppi/Downloads/singingmonsters-bot/vendor/bundle/ruby/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:975:in `run_deferred_callbacks'
	 3: from /home/joseppi/Downloads/singingmonsters-bot/vendor/bundle/ruby/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:975:in `times'
	 2: from /home/joseppi/Downloads/singingmonsters-bot/vendor/bundle/ruby/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:978:in `block in run_deferred_callbacks'
	 1: from main.rb:117:in `block in <main>'
main.rb:28:in `login': Pregame setup failed (RuntimeError)

Did I configure the file incorrectly?
![image](https://user-images.githubusercontent.com/60563147/208798734-508406e8-c741-4959-afe6-da288ce3bcc2.png)

**Comment by h-arvs** [comment]
The message "https://play.google.com/store/apps/details?id=com.bigbluebubble.singingmonsters.full" means that the client_version isn't up to date, this repo hasn't been updated in a while so there may be a few bugs. Up the client version in auth.rb to the current one, which I believe is 3.8.1, im not sure mad programmer is active also

**Comment by madprogrammer** [comment]
The code in this repo requires fixes to be compatible with the newest client, as they have introduced a new authentication algorithm. I have a new version of the bot written in different programming language, which is using an official SmartFox2X client library, which works with the newest client. I am planning to replace this repo with the new code in about a month.

**Comment by MetalMantis** [comment]
> I am planning to replace this repo with the new code in about a month.

Any update on this?

**Comment by warthog9** [comment]
I'd be interessted with helping on the code side if you can get the code out somewhere, in the meantime I've been working on getting the npm library to authenticate and connect

**Comment by freehelpdesk** [comment]
"in about a month" - programmer time

**Comment by freehelpdesk** [comment]
I have been reverse engineering the android MSM client, and it looks like they are using a lot of public frameworks for user management. i have not seen any authentication calls directly in the game that was programmed by BBB themselfs. I have also tried intercepting the app's HTTP traffic on an android device, however each time the auth call was made, it was rejected and unable to process, so i was unable to inspect the calls made. 

I am now going to try reverse engineering the iOS app and inspect its traffic using Frida. 

I will update on progress being made, i will also provide a decrypted iPA to anyone who wants it.

**Comment by h-arvs** [comment]
> I have been reverse engineering the android MSM client, and it looks like they are using a lot of public frameworks for user management. i have not seen any authentication calls directly in the game that was programmed by BBB themselfs. I have also tried intercepting the app's HTTP traffic on an android device, however each time the auth call was made, it was rejected and unable to process, so i was unable to inspect the calls made.
> 
> I am now going to try reverse engineering the iOS app and inspect its traffic using Frida.
> 
> I will update on progress being made, i will also provide a decrypted iPA to anyone who wants it.

Hey dude, I've reversed the BBB api myself with IDA and the android client and have a working client written in c#, add me on discord at **h_arvs** if you want any help.

**Comment by freehelpdesk** [comment]
Added.
